server:
  port: 8080

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost/test?useSSL=false
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/coolDB
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
