server:
  port: 8080

spring:
  application:
    name: user-service
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:TEST;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driverClassName: org.h2.Driver
    platform: h2

  h2:
    console:
      enabled: true
      settings:
        webAllowOthers: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
